### ISSUE TITLE
[Crash]: Crash on Thermos-Core 1.7.10 

### ISSUE THREAD

**Issue by 4epB9Ik** [FalsePattern/LagGogglesLegacy#2]
When trying to run a mod with the Thermos core - a server crash occurs when requesting a profile

### Crash Log

java.lang.NoSuchMethodError: net.minecraft.world.WorldServer.func_72910_y()Ljava/util/List;
	at com.falsepattern.laggoggles.util.Perms.lambda$getLagGogglesUsers$0(Perms.java:53)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at com.falsepattern.laggoggles.util.Perms.getLagGogglesUsers(Perms.java:55)
	at com.falsepattern.laggoggles.profiler.ProfileManager$1.run(ProfileManager.java:51)
	at com.falsepattern.laggoggles.util.RunInServerThread.onServerTick(RunInServerThread.java:19)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_612_RunInServerThread_onServerTick_ServerTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.postWithScan(EventBus.java:536)
	at cpw.mods.fml.common.eventhandler.EventBus.handler$beforePost$zza000(EventBus.java:560)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java)
	at cpw.mods.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:270)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:690)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:587)
	at java.lang.Thread.run(Thread.java:748)

Core sources link: [https://github.com/CyberdyneCC/Thermos](https://github.com/CyberdyneCC/Thermos)

**Comment by FalsePattern** [comment]
please attach the entire log file as requested in the issue template, otherwise i can't help

**Comment by 4epB9Ik** [comment]
There is no point in having a full log file.
The error says that the class addresses specified in the mixins are not available. The reason is that there are other mappings in the server core.

What kind of mappings are used in this kernel - threw off a link to the repository of the kernel itself.

Please adapt the mixins to the correct addresses and the error will be fixed.

P.S Full crash log [crash-2022-05-28_20.34.08-server.txt](https://github.com/FalsePattern/LagGogglesLegacy/files/8794354/crash-2022-05-28_20.34.08-server.txt)

**Comment by FalsePattern** [comment]
This mod uses the default forge modloader 10.13.4.1614-1.7.10 mcp-srg mappings as downloaded by ForgeGradle.
If you want to use it with a server that has non-standard mappings, you will need to recompile either this mod or the server with matching mappings, there are currently no plans to support third party mappings.

**Comment by FalsePattern** [comment]
closed as stale
